# Generated by Django 4.0.3 on 2022-04-29 01:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authenticate', '0001_initial'),
    ]
 
    operations = [
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.TextField()),
                ('last_name', models.TextField()),
                ('date_of_birth', models.DateField()),
                ('email', models.TextField()),
                ('phonenumber', models.TextField()),
                ('landline_phonenumber', models.TextField()),
                ('address', models.TextField()),
                ('complement', models.TextField()),
                ('zipcode', models.TextField()),
                ('neighborhood', models.TextField()),
                ('city', models.TextField()),
                ('country', models.TextField()),
                ('state', models.TextField()),
            ],
        ),
    ]
