# Generated by Django 4.0.3 on 2022-05-01 20:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authenticate', '0003_alter_patient_address_alter_patient_city_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient',
            name='complement',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='patient',
            name='landline_phonenumber',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ] 
