# Generated by Django 4.0.3 on 2022-05-03 22:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authenticate', '0004_alter_patient_complement_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='patient', 
            name='country',
        ),
    ]
